$(document).ready(function()
    {
       $('.entrance').click(function()
          {
            $('.switchscreen').animate(
                {
                  'left':'0px', 
                  'top':'0px',
                   'width':'100%',
                   'height':'100%'
                },
                500,
               function()
               {
                 window.location.assign("./letter/letter1.html"); 
                });
          });
    });
